@BaseURL=http://localhost:3000/api
@AccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInR5cGUiOiJBQ0NFU1MiLCJleHAiOjE3NDMzMjI2MDIuMzA3fQ.J5KKEHpkLqRr2127TO_O6VTaB60_FENo0LBet2vd4mk
@RefreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsImdyb3VwSUQiOiIxYjNmYzQ1Ny1mZDVjLTQ1M2YtODFiOC1hYmQzODRlOWJlNTYiLCJ0b2tlbklEIjoiNDY1YzQ1YTItZTQ5OS00NzBlLWI4NTUtYjM5MmVlNGNjMGM2IiwidHlwZSI6IlJFRlJFU0giLCJleHAiOjE3NDM5MjY1MDIuMzA5fQ.CzObPpBmYQAE47pn05T3FoIKFa3VkOay-yUHm9ZxAj0

### 新建用户
POST {{BaseURL}}/user
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}

### 登录
POST {{BaseURL}}/user/signIn
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}

### 注销
DELETE  {{BaseURL}}/user/signOut
Authorization: Bearer {{AccessToken}}
X-Refresh-Token: {{RefreshToken}}