@BaseURL=http://localhost:3000/api

### 新建用户
POST {{BaseURL}}/user
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}

### 用户登录
POST {{BaseURL}}/user/signIn
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}