@BaseURL=http://localhost:3000/api
@AccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInR5cGUiOiJBQ0NFU1MiLCJleHAiOjE3NDMxNjAyMjguOTF9.HD3xJAGYjfsdSpEAL84iCObn_CA0jAbPt7vS0day8S0
@RefreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsImdyb3VwSUQiOiIyOThmZmYzNi1kZTNmLTRlZjQtODVkZS0yZjQ4YTNmY2U4ZjgiLCJ0b2tlbklEIjoiNTVmYWJjMmMtMmM2Yy00ZmFhLWI2ZjEtMGVkNmIyYjVjMzUyIiwidHlwZSI6IlJFRlJFU0giLCJleHAiOjE3NDMxNjAyODguOTExfQ.8Nfb9uIgcu14LL7HY6ZQieYJRsrr7y8q3GvQhw27Fhk


### 心跳检测
GET {{BaseURL}}/ping

### 获取所有todo
GET {{BaseURL}}/todo
Authorization: Bearer {{AccessToken}}
X-Refresh-Token: {{RefreshToken}}

### 新建一个
POST {{BaseURL}}/todo
Content-Type: application/json

{
  "title": "第一个todo"
}

### 更新一个
PUT {{BaseURL}}/todo/1
Content-Type: application/json

{
  "completed": true,
  "title": "hhhhh"
}