@BaseURL=http://localhost:3000/api
@AccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInR5cGUiOiJBQ0NFU1MiLCJleHAiOjE3NDMxNzUxNTMuNDAzfQ.11LrJ4QxtscaebOXuJ-yhd-hORXy7aeXz-r8DUcApz4
@RefreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsImdyb3VwSUQiOiJkMTNjYzMyMy0xM2U4LTRhODctOTYzNS04NjhlOTYxMzNmNDkiLCJ0b2tlbklEIjoiMzMwMDhmYmItZjYwZS00M2VkLTk2MjEtMGRhMWY3NWYwZWM4IiwidHlwZSI6IlJFRlJFU0giLCJleHAiOjE3NDM3NzkwNTMuNDA0fQ.2PkRR0suSutZBXEHeNJMG5v-obgm0NBd6B3ayDZExA0
@AccessToken1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjIsInR5cGUiOiJBQ0NFU1MiLCJleHAiOjE3NDMxNzU5MDQuMTk2fQ.Tpkf8e0aYgLrMMHu59o0cCsulskCrVlotWbGZR36nRQ
@RefreshToken1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjIsImdyb3VwSUQiOiI5ODI1MjRjZC1iOTZlLTQyZWMtYjk5MS04MDZhYjEyNmUzMzIiLCJ0b2tlbklEIjoiNmQ5ZWM1NTUtYTEwZS00OWEyLTlkNWItZGQ3YzdlYTMwNzE4IiwidHlwZSI6IlJFRlJFU0giLCJleHAiOjE3NDM3Nzk4MDQuMTk4fQ.I3ztquENTWiAtCx80cKnR5-Acly7mXpqM4VQPTHjILw


### 心跳检测
GET {{BaseURL}}/ping

### 获取所有todo
GET {{BaseURL}}/todo
Authorization: Bearer {{AccessToken1}}
X-Refresh-Token: {{RefreshToken1}}

### 新建一个
POST {{BaseURL}}/todo
Content-Type: application/json
Authorization: Bearer {{AccessToken1}}
X-Refresh-Token: {{RefreshToken1}}

{
  "title": "这是用户test的todo"
}

### 更新一个
PUT {{BaseURL}}/todo/3
Content-Type: application/json
Authorization: Bearer {{AccessToken1}}
X-Refresh-Token: {{RefreshToken1}}

{
  "completed": true,
  "title": "改为用户2的todo"
}