@BaseURL=http://localhost:3000/api
@Auth=Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsImV4cCI6MTc0MzY3MTM2NH0.TSHUPWCpHoQ_BaPSNq5zYKiAORrTYVKkn5hfwLQjbRA

### 登录
POST {{BaseURL}}/auth/signIn
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "12345678"
}

### 退出登录
DELETE {{BaseURL}}/auth/signOut
{{Auth}}