@BaseURL=http://localhost:3000/api

### Sign Up
POST {{BaseURL}}/user/sign-up
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "12345678"
}

### Sign In
POST {{BaseURL}}/user/sign-in
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "12345678"
}

### Sign out
PUT {{BaseURL}}/user/sign-out