@BaseURL=http://localhost:3000/api
@Auth=Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjcsImV4cCI6MTc0MzY2ODUyOH0.0hECMVHX6YZJZKUB39qMl2wawEGtPkltWtArDnJbkjs

### 心跳检测
GET {{BaseURL}}/ping

### 获取所有todo
GET {{BaseURL}}/todo
{{Auth}}