@BaseURL=http://localhost:3000/api
@Auth=Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsImV4cCI6MTc0MzY3MTM2NH0.TSHUPWCpHoQ_BaPSNq5zYKiAORrTYVKkn5hfwLQjbRA

### 心跳检测
GET {{BaseURL}}/ping

### 获取所有todo
GET {{BaseURL}}/todo
{{Auth}}