@BaseURL=http://localhost:3000/api

@AccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInR5cGUiOiJBQ0NFU1MiLCJleHAiOjE3NDMxNjAwODcuNTQ0fQ.3wZp_UfF-_TrdSfumpOHNC0S_-QzeY0EMZ3mDmZe8tg
@RefreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsImdyb3VwSUQiOiIwNTU2NmRmZS1iODNjLTQ3MTktYTQ1Ni1mMTUzNWY2ZDk4ODQiLCJ0b2tlbklEIjoiNTVhZGI4YjUtNzEyMi00YzViLThhZmItMTY4YWQzYTE1NDg3IiwidHlwZSI6IlJFRlJFU0giLCJleHAiOjE3NDMxNTk5NDguOTI0fQ.w99jnbG3bHSzBKNGBWnm_iDK0JRsGaGkgrGhV-KvdRw

### 登录
POST {{BaseURL}}/auth/signIn
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "12345678"
}

### 退出登录
DELETE {{BaseURL}}/auth/signOut
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsImV4cCI6MTc0MzY3MjQ0MH0.D3WWevbzJmXBvOY27H-CpgnM4AjT-tnna2ePzs_xqgc